apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    ports:
      web:
        exposedPort: 8000
        expose: true
      websecure:
        exposedPort: 8443
        expose: true
    logs:
      general:
        level: DEBUG
    additionaArguments:
      - "--providers.kubernetescrd.allowCrossNamespace=true"
