apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
  labels:
    app: tlc
    component: front
    {{- include "doodlestudent.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector: 
    matchLabels:
      component: front
  template:
    metadata:
      labels:
        component: front
    spec:
      serviceAccountName: {{ include "doodlestudent.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}-front
          image: "{{ .Values.image.registry }}/tlc_front:latest"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          #livenessProbe:
            #httpGet:
            #  host: api
            #  path: /
            #  port: 8080
          readinessProbe:
            httpGet:
              path: /
              port: http