apiVersion: v1
kind: Service
metadata:
  name: etherpad
  labels:
    component: etherpad
    {{- include "doodlestudent.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 9001
    targetPort: 9001
    protocol: TCP
  selector:
    component: etherpad