apiVersion: apps/v1
kind: Deployment
metadata:
  name: etherpad
  labels:
    app: tlc
    component: etherpad
    {{- include "doodlestudent.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector: 
    matchLabels:
      component: etherpad
  template:
    metadata:
      labels:
        component: etherpad
    spec:
      serviceAccountName: {{ include "doodlestudent.serviceAccountName" . }}
      containers:
      - name: {{ .Chart.Name }}-etherpad
        image: etherpad/etherpad:latest
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - name: http
            containerPort: 9001
            protocol: TCP
        volumeMounts:
        - name: apikey
          mountPath: /opt/etherpad-lite/APIKEY.txt
          subPath: apikey-file
      volumes:
      - name: apikey
        configMap:
          name: etherpad-cfgmap