apiVersion: v1
kind: Service
metadata:
  name: mail
  labels:
    component: mail
    {{- include "doodlestudent.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 2525
    targetPort: 25
    protocol: TCP
  selector:
    component: mail