apiVersion: v1
kind: Service
metadata:
  name: myadmin
  labels:
    component: myadmin
    {{- include "doodlestudent.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    component: myadmin