apiVersion: apps/v1
kind: Deployment
metadata:
  name: back
  labels:
    app: tlc
    component: back
    {{- include "doodlestudent.labels" . | nindent 4 }}
spec:
  replicas: 3
  selector: 
    matchLabels:
      component: back
  template:
    metadata:
      labels:
        component: back
    spec:
      serviceAccountName: {{ include "doodlestudent.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}-back
          image: "{{ .Values.image.registry }}/tlc_back:latest"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 8080