apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    component: back
    {{- include "doodlestudent.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    component: back
