
name: build-update-back

on:
  push:
    branches: main
    paths: '/doodlestudent/api/**'
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Login to private registry
        uses: docker/login-action@v1
        with:
          registry: registry.carryboo.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./doodlestudent/docker/back/
          file: ./doodlestudent/docker/back/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: '${{ secrets.REGISTRY_URL }}/tlc_light/tlc_back:latest'
          cache-from: 'type=registry,ref=${{ secrets.REGISTRY_URL }}/tlc_light/tlc_back:buildcache'
          cache-to: 'type=registry,ref=${{ secrets.REGISTRY_URL }}/tlc_light/tlc_back:buildcache,mode=max'
