name: test-GA

on:
  push:
    branches:
    - main
    paths:
    - ./**

jobs:
  deploy:
    runs-on: self-hosted

    env:
      KUBECONFIG_FILE: '${{ secrets.CARRYBOO_KUBECONFIG }}'

    steps:
    - name: Checkout
      uses: actions/checkout@v2
