name: test-GA

on:
  push:
    branches:
    - main
    paths:
    - './doodlestudent/api/**'

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v2
